---
abstract: 'Compare various stopword list modules'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Benchmark-Featureset-StopwordLists
provides:
  Benchmark::Featureset::StopwordLists:
    file: lib/Benchmark/Featureset/StopwordLists.pm
    version: 1.01
  Benchmark::Featureset::StopwordLists::Config:
    file: lib/Benchmark/Featureset/StopwordLists/Config.pm
    version: 1.01
requires:
  Config: 0
  Config::Tiny: 2.13
  Date::Simple: 3.03
  File::Copy: 2.21
  File::HomeDir: 0.99
  Hash::FieldHash: 0.12
  Lingua::EN::StopWordList: 1
  Lingua::EN::StopWords: 0.1
  Lingua::StopWords: 0.09
  Module::Version: 0.12
  Path::Class: 0.24
  Text::Xslate: 1.501
  strict: 1.04
  warnings: 1.12
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.01
